# Generated by Django 4.2.1 on 2023-06-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField(default=None)),
                ('name', models.TextField(max_length=999)),
                ('summary', models.CharField(max_length=140)),
                ('description', models.TextField(max_length=999)),
                ('url', models.URLField()),
                ('start_date', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('currency', models.CharField(max_length=140)),
                ('online_event', models.BooleanField()),
                ('listed', models.BooleanField()),
                ('shareable', models.BooleanField()),
                ('capacity', models.IntegerField()),
                ('event_logo', models.ImageField(default=None, upload_to='')),
            ],
        ),
    ]
