# Generated by Django 4.2.1 on 2023-06-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='capacity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.CharField(default=None),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_logo',
            field=models.ImageField(default='No logo provided', max_length=512, upload_to=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='url',
            field=models.URLField(max_length=512),
        ),
    ]
